# RGB LED Widgetの機能を有効化
CONFIG_RGBLED_WIDGET=y

# 40%以下で黄色、20%以下で赤色に設定（名称を修正しました）
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=40
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=2

# LEDアンダーグロー機能を有効化
CONFIG_ZMK_RGB_UNDERGLOW=y

# キーボード起動時のLEDデフォルト状態
# 電池持ちを考慮し、USBを挿した時だけ明示的にオンにしたい場合はオフがおすすめです
CONFIG_ZMK_RGB_UNDERGLOW_AUTO_OFF_USB=y

# 1. ハードウェアとしての最大輝度を「60%」に制限する
CONFIG_ZMK_RGB_UNDERGLOW_BRT_MAX=20

# 2. 起動時の初期の明るさを、制限後の最大値（70%）に対して「30%」の明るさにする
CONFIG_ZMK_RGB_UNDERGLOW_BRT_START=5
