# RGB LED Widgetの機能を有効化
CONFIG_RGBLED_WIDGET=y

# 40%以下で黄色、20%以下で赤色に設定（名称を修正しました）
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=40
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_LOW=2

# LEDアンダーグロー機能を有効化
CONFIG_ZMK_RGB_UNDERGLOW=y

# 外部電源（USB給電）がないときは自動でLEDへの出力をオフにする
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER_TOGGLE=y
