# バッテリーLED表示機能を有効化
CONFIG_ZMK_RGBLED_WIDGET=y

# 40%以下で黄色、20%以下で赤色に設定
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_HIGH=40
CONFIG_RGBLED_WIDGET_BATTERY_LEVEL_CRITICAL=20

# スリープ復帰時にも自動で残量を点滅表示する
CONFIG_RGBLED_WIDGET_SHOW_ON_WAKE=y
